spring:
  datasource:
    url: jdbc:postgresql://34.64.75.124:5432/postgresql
    # url: jdbc:postgresql://localhost:5432/postgresql
    username: postgresql
    password: postgrespassword
  jpa:
    show-sql: false
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      ddl-auto: update
  rabbitmq:
    # host: localhost
    host: 34.85.105.229
    username: guest
    password: guest
    port: 5672
  data:
    elasticsearch:
      hosts: 10.146.0.3,10.146.0.4,10.146.0.6,10.146.0.7
      port: 9200